project:
  type: website
  output-dir: docs

website:
  title: "Global Health and Demography"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures/week01_population_pyramid.qmd
        text: Week 1. Population Pyramid
      - href: lectures/week02_mortality_fertility.qmd
        text: Week 2. Mortality and Fertility