---
title: "Global Health and Demography"
author: "MJ"
format: html
editor: visual
---

## I. Course overview

1.  Course objectives

    By the end of this course, students will be able to:

    1\) Understand how demographic change shapes global health challenges and opportunities

    2\) Analyze population and health data using **R** and **GeoDa**

    3\) Explain and demonstrate the health consequences of demographic transitions

2.  Course Schedule

    1\) We**e**k 1 **(May 26):** Introduction to Global Health and Demography

    2\) Week 2 (**June 9):** Contemporary Fertility and Mortality Transition

    3\) Week 3 (**June 16):** Mobility, Migration, and Health

    4\) Week 4 (**June 23):** Spatial Demography and Health

## II. Lecture materials

-   Lecture slides will be shared via email before each class. Please check your email regularly.

-   Course materials and practical tutorials are available at:

    [**https://myunggu82.github.io/global-health-demography/**](https://myunggu82.github.io/global-health-demography/)

## III. Evaluation

-   평가: P/F (출석 30%, 평가 70%)

-   출석: 수업 일수 1/2 (2번) 이상 결석한 경우, 사유와 상관없이 F학점 부여 (서울의대 선택교과 출결 원칙 2020. 실행)

-   최종성찰보고서

    -   학생 작성 시기:과목 종료 후 (마지막 수업 후)

    -   양식: A4 한장 이내

    -   제출기한: 마지막 수업 당일 까지 (최종 제출 기한은 ETL 통해 일괄 공지 예정)

## IV. Reading materials (Option)

-   팩트풀니스 (한스로슬링, 2018)

-   죽음의 역사 (앤드류 도이그, 2023)

-   출산, 그 놀라운 역사 (티나 캐시디, 2007)

-   How Population Change Will Transform Our World (Sarah Harper, 2016)

-   Why Demography Matters (Danny Dorling, Stuart Gietel-Basten ,2018)

## V. Contacts

-   Prof. Young Su Park (youngsupark\@snu.ac.kr)

-   Dr. Myunggu Jung (myunggu82\@snu.ac.kr)
